development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL_SCHEME'] || 'http' %>://<%= ENV['FEDORA_HOST'] || '127.0.0.1' %>:<%= ENV['FEDORA_PORT'] || '8984' %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL_SCHEME'] || 'http' %>://<%= ENV['FEDORA_HOST'] || '127.0.0.1' %>:<%= ENV['FEDORA_PORT'] || '8986' %>/rest
  base_path: /test
production:
  user: <%= ENV.fetch('FEDORA_USER', 'fedoraAdmin') %>
  password: <%= ENV.fetch('FEDORA_PASSWORD', 'fedoraAdmin') %>
  url: <%= ENV['FEDORA_URL_SCHEME'] || 'http' %>://<%= ENV['FEDORA_HOST'] || 'fcrepo' %>:<%= ENV['FEDORA_PORT'] || '8080' %>/fcrepo/rest
  base_path: /production
