development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL_SCHEME'] || 'http' %>://<%= ENV['FCREPO_HOST'] || '127.0.0.1' %>:<%= ENV['FCREPO_PORT'] || '8984' %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL_SCHEME'] || 'http' %>://<%= ENV['FCREPO_HOST'] || '127.0.0.1' %>:<%= ENV['FCREPO_PORT'] || '8986' %>/rest
  base_path: /test
production:
  user: <%= ENV.fetch('FCREPO_USER', 'fedoraAdmin') %>
  password: <%= ENV.fetch('FCREPO_PASSWORD', 'fedoraAdmin') %>
  url: <%= ENV['FCREPO_URL_SCHEME'] || 'http' %>://<%= ENV['FCREPO_HOST'] || 'fcrepo' %>:<%= ENV['FCREPO_PORT'] || '8080' %><%= ENV['FCREPO_PATH'] || '/fcrepo/rest' %>
  base_path: /<%= ENV['FCREPO_ENDPOINT'] || 'production' %>
