---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS",5) %>
:queues:
  - default
  - scheduled
production:
  :concurrency: 1
  :verbose: false
  :pidfile: <%= File.join(ENV.fetch('PIDS_PATH', 'tmp'), 'sidekiq.pid') %>
